FROM nginx
COPY ./default.conf /etc/nginx/conf.d/
RUN echo 'zhe shi yi ge nginx jing xiang' > /usr/share/nginx/html/index.html
# RUN echo 'zhe shi yi ge nginx jing xiang' > /index.html
# RUN echo 'zhe shi yi ge nginx jing xiang' > /usr/share/nginx/index.html
# RUN echo 'zhe shi yi ge nginx jing xiang' > /etc/nginx/html/index.html
EXPOSE 8088